services:
  db-menu:
    image: postgres:16-alpine
    container_name: db-menu
    ports:
      - 5432:5432
    env_file:
      - .local.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - event-menu

  api-menu:
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    container_name: api-menu
    command: /bin/sh /start.sh
    stdin_open: true
    tty: true
    ports:
      - 8001:8000
    env_file:
      - .local.env
    volumes:
      - ./api:/app
    depends_on:
      - db-menu
    networks:
      - event-menu
    
  web-menu:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    container_name: web-menu
    command: /bin/sh /start.sh
    ports:
      - 5500:5500
    volumes:
      - ./web:/app
    depends_on:
      - db-menu
      - api-menu
    networks:
      - event-menu

networks:
  event-menu:
    driver: bridge
