services:
  db-menu-local:
    image: postgres:16-alpine
    container_name: db-menu-local
    ports:
      - 5432:5432
    env_file:
      - .local.env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - event-menu

  api-menu-local:
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    container_name: api-menu-local
    command: /bin/sh /start.sh
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .local.env
    volumes:
      - ./api:/app
    depends_on:
      - db-menu-local
    networks:
      - event-menu
    
  web-menu-local:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    container_name: web-menu-local
    command: /bin/sh /start.sh
    ports:
      - 5500:5500
    volumes:
      - ./web:/app
    depends_on:
      - db-menu-local
      - api-menu-local
    networks:
      - event-menu

  cache-menu-local:
    image: redis:7-alpine
    container_name: cache-menu-local
    ports:
      - 6379:6379
    networks:
      - event-menu

networks:
  event-menu:
    driver: bridge
