services:
  db-menu:
    image: postgres:16-alpine
    container_name: db-menu
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - event-menu

  api-menu:
    build:
      context: .
      dockerfile: ./docker/production/api/Dockerfile
    container_name: api-menu
    command: /bin/sh /start.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./staticfiles:/staticfiles/
      - ./mediafiles:/mediafiles/
    depends_on:
      - db-menu
    networks:
      - event-menu

networks:
  event-menu:
    driver: bridge

volumes:
  db:
