# Generated by Django 5.0.4 on 2024-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
